// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1adpPmmHksajdonf4gIrk_sz2tlxF0IA',
    appId: '1:844550940234:web:b9e3047af83af443ff28b3',
    messagingSenderId: '844550940234',
    projectId: 'fashion-store-cit211-dee13',
    authDomain: 'fashion-store-cit211-dee13.firebaseapp.com',
    storageBucket: 'fashion-store-cit211-dee13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7d2XKnMU61fQNo6PNWWfTk3jhUkjmT0g',
    appId: '1:844550940234:android:c4c4f7777b639c0eff28b3',
    messagingSenderId: '844550940234',
    projectId: 'fashion-store-cit211-dee13',
    storageBucket: 'fashion-store-cit211-dee13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNCj-NW5yuuU1q5yNqNErv5lo3UKhRh-I',
    appId: '1:844550940234:ios:313c2ad8446bf2a0ff28b3',
    messagingSenderId: '844550940234',
    projectId: 'fashion-store-cit211-dee13',
    storageBucket: 'fashion-store-cit211-dee13.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNCj-NW5yuuU1q5yNqNErv5lo3UKhRh-I',
    appId: '1:844550940234:ios:313c2ad8446bf2a0ff28b3',
    messagingSenderId: '844550940234',
    projectId: 'fashion-store-cit211-dee13',
    storageBucket: 'fashion-store-cit211-dee13.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1adpPmmHksajdonf4gIrk_sz2tlxF0IA',
    appId: '1:844550940234:web:ad13b1d68a5d7396ff28b3',
    messagingSenderId: '844550940234',
    projectId: 'fashion-store-cit211-dee13',
    authDomain: 'fashion-store-cit211-dee13.firebaseapp.com',
    storageBucket: 'fashion-store-cit211-dee13.firebasestorage.app',
  );

}